<a href="https://colab.research.google.com/github/aldisulthony/Pemrograman-Python/blob/main/Aldi_Sulthony_Susilo_1101172222_Image_Classification_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Google Drive cloud database

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Importing the folder that contains the dataset needed for image classification modeling

In [2]:
cd /content/drive/MyDrive/data

/content/drive/MyDrive/data


List the folder to makesure that the dataset includes in the specified folder

In [3]:
ls

 3scene/
'Aldi Sulthony Susilo_1101172222_Image Classification 2.ipynb'
 best_weight_scene_mobileNet.h5
 dataset/
 forest_test.jpg
 nnmodel_scene/


In [4]:
# Import necessary modules and packages
from keras.models import Sequential
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from PIL import Image
from imutils import paths
import numpy as np
import os

In [5]:
# Create the image path with "paths" in the input data dataset directory
# List the images and its labels
print("[INFO] loading images..")
imagePaths = paths.list_images("dataset")
data = []
labels = []

[INFO] loading images..


In [6]:
# Loop over the input images using "for" function:
for imagePath in imagePaths:
  # Load the input image from the selected image path
  image = Image.open(imagePath)

  # Resize it to 64x64 pixels, the pixel intensities to the range [0,1] and then updateour image list
  # Conducting the prepocessing and normalize process to the image
  image = np.array(image.resize((64,64))) / 255.0 
  data.append(image)

  # Extract the class label from the path file and update the labels list
  label = imagePath.split(os.path.sep)[-2]
  labels.append(label)

In [7]:
# Visualize the input image label list
print(labels)

['GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10', 'GMB_10',

In [8]:
# Encode the input image labels, convert them from strings to integers to make easier for computer to proceed
lb = LabelBinarizer()
labels = lb.fit_transform(labels)

In [9]:
# Visualize the converted input label images
print(labels)

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [28]:
# Perform a training and testing split data for modeling
# Using 75% of the data for training and 25% of the data for evaluation
(trainX, testX, trainY, testY) = train_test_split(np.array(data), np.array(labels), test_size=0.25, shuffle=True)

# Visualize train and test X shape
print(trainX.shape)
print(testX.shape)

(1055, 64, 64, 3)
(352, 64, 64, 3)


In [29]:
# Conducting Convolutional Neural Network and Fully Connected Feedforward Network

# Import necessary modules and packages
from keras.layers import Convolution2D, MaxPooling2D
from keras.models import Sequential
from keras.layers.core import Flatten, Dense

# Proceed the CNN stages (2 times of Convolution and Max Pooling)
model = Sequential()
model.add(Convolution2D(8, (3,3), activation='relu', input_shape=(64,64,3)))
model.add(MaxPooling2D(2,2))
model.add(Convolution2D(16, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

# Conduct the Fully Connected Layer stages
model.add(Flatten()) # remap the weight to 1D
model.add(Dense(100, activation='relu'))
model.add(Dense(5, activation='softmax')) # 5 for attributes that is use for this modeling

# Perform the model summary
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_12 (Conv2D)           (None, 62, 62, 8)         224       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 31, 31, 8)         0         
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 29, 29, 16)        1168      
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 14, 14, 16)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 3136)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 100)               313700    
_________________________________________________________________
dense_3 (Dense)              (None, 5)               

In [34]:
# Train the model using the Adam Optimizer
print("[INFO] training network...")
opt = Adam(lr=1e-3, decay=1e-3 / 50)
model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
H = model.fit(trainX, trainY, validation_data=(testX, testY), epochs=25, batch_size=32)

[INFO] training network...
Epoch 1/25


ValueError: ignored

In [ ]:
# Visualixe the trained model

# Import Matplotlib
import matplotlib.pyplot as plt

print(H.history.keys())

# Summarize history for accuracy
plt.plot(H.history['accuracy'])
plt.plot(H.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

# Summarize history for loss
plt.plot(H.history['loss'])
plt.plot(H.history['val_loss'])
plt.title('Modell Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

In [ ]:
# Evaluate the model by using F1 Score Table
print('[INFO] Evaluating Network...')
predictions = model.predict(testX, batch_size=32)
print(classification_report(testY.argmax(axis=1), predictions.argmax(axis=1), target_names=lb.classes_))

In [ ]:
# Save the Model
model.save('cnnmodel_leaf')

In [ ]:
# Perform image testing by using the saved moddel by using cv2

# Import necessary modules
import cv2
import matplotlib.pyplot as plt 
image_test = 'leaf_test.jpg'

In [ ]:
# Read and Show the image test file by using cv2 module
img_array = cv2.imread(image_test)

# Read and show the array based image using matplotlib module
plt.imshow(img_array)
plt.show()

In [ ]:
image_testing = Image.open('leaf_test.jpg')
image_testing = np.array(image_testing.resize((64,64))) / 255.0 # based on the image trained model size and normalize phase
image_testing.shape # show the testing image shape 

In [ ]:
image_testing = np.expand_dims(image_testing, axis=0)
print(image_testing.shape)

In [ ]:
output = model.predict(image_testing, 1)
print(output)
print(lb.classes_[output.argmax(Axis=1)])